app = "ideamark-mcp-server"
primary_region = "sjc"

[build]
  dockerfile = "lib/mcp_server/Dockerfile"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  LOG_LEVEL = "INFO"
  WORK_DIR = "/app/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[mounts]
  source = "ideamark_data"
  destination = "/app/data"
