merge:
  default_intent: union
  default_strategy: prefer
  
llm:
  providers:
    openai:
      model: gpt-4
      max_tokens: 2000
      temperature: 0.3
    anthropic:
      model: claude-3-sonnet-20240229
      max_tokens: 2000
      temperature: 0.3
  fallback_strategy: manual
  
network:
  retries: 3
  backoff_factor: 2
  timeout: 30
  
logging:
  level: INFO
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
  console: true
  file: false
  
output:
  create_summary: true
  validate_output: true
