synthesis:
  problem_summary: |
    Combine the following IdeaMark problem summaries into a single, coherent summary that captures the essence of both problems. Use a concise style and focus on the core issues.
    
    Pattern A: {text_a}
    Pattern B: {text_b}
    
    Provide only the synthesized summary without additional commentary.
    
  solution_approach: |
    Combine the following IdeaMark solution approaches into a unified approach that integrates both strategies. Use a concise style and focus on actionable methods.
    
    Pattern A: {text_a}
    Pattern B: {text_b}
    
    Provide only the synthesized approach without additional commentary.
    
  metadata_field: |
    Combine the following metadata values into a single, coherent value that represents both inputs. Use a concise style.
    
    Field: {field_name}
    Value A: {text_a}
    Value B: {text_b}
    
    Provide only the synthesized value without additional commentary.
